language: html
sudo: false
install: true

addons:
  sonarcloud:
    organization: "fbab_personal_org"
    token:
      secure: "oIBZXpBoPsflFLFytAqJkRoBpnv40iJk4SlrS+lAaZr1VpwVUk/eprFcEqExU5t6s+cA4Rf7JsV9HfVY121kMirIZXtVc5EBg1o6ijvuawfbSUd4186Atgxmjw77Ib/BMRoSYaQBHGHqhOJ/1ScP80vTyuSK8RGMozuxNg6quFaPCECi6mveCha1J34E0MngAV43G4hmAK7E4EAJhZY0k6x3Eu3O8uzPZ4jYN0fVBnnGFFJtGZK3SQKTrFSBj9kIgGMSK6DSSavrGrrYyOt+wkfx+rdecMuKGTmW8A01lrjIuf0ADKlASfCp7MxgtZeH9rzyZepTLUrmFUdTOwsjSrJF1DtD0p5YSPbEB8RujcU4RsfX198gIOS1/fbGl4g9+W3DocVkR9Nc6cWD2DAx6w2lqwAeUddyNTDjqVqzqw2DOalD2CVN46cLOH77BEUrpMblBtzJsfMkd3TGGyfHkKrQ/qJpmiQdrEMmPaNkx5Qv48dKTNbts+/aVMPGhc+hbuTMvTUCSAZe3YPavVrlkKVdxh/ulKPOqGXyJ9xLRj0KckaB7hKCQlyKBuGJiY4NmiN0f6viJBGZOfnd/gpOhy6R20kAHNItSRfpDzyLG35r7WC3p/MAYQOfoJLw76jz8mkfnPP3EdFPDYSNCy7LStz9f1ejfhro57ffNKoBGEc="
      # secure: "jCe1bGGbx0kwEDy9PDcXBlX5YAkjbEX2moL93L8U+UwkmDRbilsSQQYKQtzgUJ4drUU8g0BJywndUBcR0DSF1dW9YjPGgazCrCbiSimXy3IFMwLI5kU2BnJXTHzcQDJDxWr4P5UttL1KsXi72dRTmeTa9XvXckTCkggAPsprTTA/aurYBuh5C8JbK3WKLwctEmC8RcYLg92cK9H09493h+Txk/jmRoS9wisXwPEbJu5+XspUOgBfrfGYMhKs+cJfaIJs7nRdb7nu65opb+SfgiFurYpKKQ1VJuJp9VAHlQ3Uu6XxItDq4Q0wSHI9an5QjzFuQNxsBORTvB6R99PZlgcAtV6jWRRUhn7QKh+7ibviBcKBCwUw+1j57cxIPXEu5CaG9KyCZQSzLpFCx7zk2mKsPatnHc8ucaDCxBRJnkT9ZfVg5V8ac4wqwqfzmoiNUpHQZ1V0pWHdH9iPChMW1+cYmCmxOMDscE5vx4E4aTKySFgfsZQRwDhMm1zm7WPiUNPy2rez5GAhNLKIGhBV3+6DFYdaitrNDet68uvthaRbrzOrhJ8WUAvW2qCnqPJ3FUecOoJCrTxpthIBjsA9EXFaly70DeINdTY6TM5Jyv8OzLTG3xYPlL6OgFoFPKG90pQLVvAgI4pSccERFOqcf57wuxymQWy2aHLjLMyeX+s="


script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  # - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
  - sonar-scanner
