dist: trusty
sudo: required

addons:
  sonarcloud:
    # info obtenue sur https://sonarcloud.io/account/security
    organization: "fbab-github"
    # token:
      # cl√© du projet prodageo/EXA5008
      # secure: "G4ZUdjYSmT1EghKI3owHc/kuwMEqv04iALFIx6RFwB39SP73XORL1abcI/Z/Ugu7AId4GWl9lcrtcWTfx2VeuJEO6pUHMzh3cJzxzNhn17ruBqvSPA7jHpQADHncR3RAwbaM9qpO7f1/GqJPFoUrG23eKkR7fmh+EfoI+WzZ51ZoGDX6SR0WN6mMqs3242Vax/cosvDP5Xzj2aRQz/GGVt2FRggpXUOt1nLiUYuwmyaTJOQ5pGwqS4bFKfvfcdtBTYUPS9JKbC8aUtiL1WvCxHZNuHnNnPejExhlMxGyVGPz6NO0DgmjDNpSnxWJ9WQoL5kvAX5Pvgon5r1VuqG52xiCU5IugHi705x299zorPmukfFMwqTMjSoPYDwzheoV+6ZF0og6s6K0vk5VeJrmyMQfsDoxOsTv6MVztNUrkKRsTXhnszkF8SR2aBPPgmRjIehVm/4w1V1szfvaLLHmgGdlIZMHvrOaCmPw+dfJzxzCW+7+D0X9u555t/TIeqfJWHJL3zcJkNbFGxzarRd1H2XxjZy/aqDrKNeIxlykApu4N61gF8F5NHuZWZre9Hki3V7GqjYFdccsqVL3OURq7FHy8u9NtfM6D1HGtb3sDP02lVMKJw7hNKz3pRikil/AQpf7JW4aVDjxJBYqxV8I5NxtgxBvgWPPxDV5umWAkc4="
      # secure: "oIBZXpBoPsflFLFytAqJkRoBpnv40iJk4SlrS+lAaZr1VpwVUk/eprFcEqExU5t6s+cA4Rf7JsV9HfVY121kMirIZXtVc5EBg1o6ijvuawfbSUd4186Atgxmjw77Ib/BMRoSYaQBHGHqhOJ/1ScP80vTyuSK8RGMozuxNg6quFaPCECi6mveCha1J34E0MngAV43G4hmAK7E4EAJhZY0k6x3Eu3O8uzPZ4jYN0fVBnnGFFJtGZK3SQKTrFSBj9kIgGMSK6DSSavrGrrYyOt+wkfx+rdecMuKGTmW8A01lrjIuf0ADKlASfCp7MxgtZeH9rzyZepTLUrmFUdTOwsjSrJF1DtD0p5YSPbEB8RujcU4RsfX198gIOS1/fbGl4g9+W3DocVkR9Nc6cWD2DAx6w2lqwAeUddyNTDjqVqzqw2DOalD2CVN46cLOH77BEUrpMblBtzJsfMkd3TGGyfHkKrQ/qJpmiQdrEMmPaNkx5Qv48dKTNbts+/aVMPGhc+hbuTMvTUCSAZe3YPavVrlkKVdxh/ulKPOqGXyJ9xLRj0KckaB7hKCQlyKBuGJiY4NmiN0f6viJBGZOfnd/gpOhy6R20kAHNItSRfpDzyLG35r7WC3p/MAYQOfoJLw76jz8mkfnPP3EdFPDYSNCy7LStz9f1ejfhro57ffNKoBGEc="
      # secure: "jCe1bGGbx0kwEDy9PDcXBlX5YAkjbEX2moL93L8U+UwkmDRbilsSQQYKQtzgUJ4drUU8g0BJywndUBcR0DSF1dW9YjPGgazCrCbiSimXy3IFMwLI5kU2BnJXTHzcQDJDxWr4P5UttL1KsXi72dRTmeTa9XvXckTCkggAPsprTTA/aurYBuh5C8JbK3WKLwctEmC8RcYLg92cK9H09493h+Txk/jmRoS9wisXwPEbJu5+XspUOgBfrfGYMhKs+cJfaIJs7nRdb7nu65opb+SfgiFurYpKKQ1VJuJp9VAHlQ3Uu6XxItDq4Q0wSHI9an5QjzFuQNxsBORTvB6R99PZlgcAtV6jWRRUhn7QKh+7ibviBcKBCwUw+1j57cxIPXEu5CaG9KyCZQSzLpFCx7zk2mKsPatnHc8ucaDCxBRJnkT9ZfVg5V8ac4wqwqfzmoiNUpHQZ1V0pWHdH9iPChMW1+cYmCmxOMDscE5vx4E4aTKySFgfsZQRwDhMm1zm7WPiUNPy2rez5GAhNLKIGhBV3+6DFYdaitrNDet68uvthaRbrzOrhJ8WUAvW2qCnqPJ3FUecOoJCrTxpthIBjsA9EXFaly70DeINdTY6TM5Jyv8OzLTG3xYPlL6OgFoFPKG90pQLVvAgI4pSccERFOqcf57wuxymQWy2aHLjLMyeX+s="

jdk:
  - oraclejdk8

script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  # - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
  - sonar-scanner -X
